ruby '2.0.0'
source 'https://rubygems.org'
gem 'sinatra', '1.4.3'
gem 'sinatra-contrib'
gem 'puma'
gem 'pg'
gem 'haml'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'redis'
gem 'newrelic_rpm'
#gem 'dm-sqlite-adapter'
